sampling_rate:
  rip: 21.33
  motionsense_accel: 25
  motionsense_gyro: 25

thresholds:
  fast_size: 20
  slow_size: 205

stream_names:
  #INPUTS
  motionsense_hrv_accel_left: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_gyro_left: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_accel_right: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_gyro_right: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"

  #### OUTPUTS STREAM NAMES
  puffmarker_wrist_feature_left: "PUFFMARKER-WRIST-FEATURE-LEFT"
  puffmarker_wrist_smoking_puff_left: "PUFFMARKER-WRIST-SMOKING-PUFF-LEFT"
  puffmarker_wrist_smoking_episode_left: "PUFFMARKER-WRIST-SMOKING-EPISODE-LEFT"

  puffmarker_wrist_feature_right: "PUFFMARKER-WRIST-FEATURE-RIGHT"
  puffmarker_wrist_smoking_puff_right: "PUFFMARKER-WRIST-SMOKING-PUFF-RIGHT"
  puffmarker_wrist_smoking_episode_right: "PUFFMARKER-WRIST-SMOKING-EPISODE-RIGHT"

description:
  puffmarker_wrist_feature_vector: "This module computes wrist feature vector of puffmarker"
  puffmarker_wrist: "puffmarker detects smoking episodes from wrist worn accelerometer and gyroscope"



