sampling_rate:
  rip: 21.33
  motionsense_accel: 25
  motionsense_gyro: 25

thresholds:
  fast_size: 20
  slow_size: 205

stream_names:
  #INPUTS
  motionsense_hrv_accel_left: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_gyro_left: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_accel_right: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_gyro_right: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"

  #### OUTPUTS STREAM NAMES
  puffmarker_wrist_feature_left: "PUFFMARKER-WRIST-FEATURE-LEFT"
  puffmarker_wrist_smoking_puff_left: "PUFFMARKER-WRIST-SMOKING-PUFF-LEFT"
  puffmarker_wrist_smoking_episode_left: "PUFFMARKER-WRIST-SMOKING-EPISODE-LEFT"

  puffmarker_wrist_feature_right: "PUFFMARKER-WRIST-FEATURE-RIGHT"
  puffmarker_wrist_smoking_puff_right: "PUFFMARKER-WRIST-SMOKING-PUFF-RIGHT"
  puffmarker_wrist_smoking_episode_right: "PUFFMARKER-WRIST-SMOKING-EPISODE-RIGHT"

algo_type:
  battery_marker: battery
  attachment_marker: attachment
  sensor_unavailable_marker: sensor_unavailable
  packet_loss_marker: packet_loss
  app_availability_marker: app_availability_marker
  sensor_failure: sensor_failure
  phone_screen_touch: phone_screen_touch


description:
  puffmarker_wrist_feature_vector: "This module computes wrist feature vector of puffmarker"
  puffmarker_wrist: "puffmarker detects smoking episodes from wrist worn accelerometer and gyroscope"
  data_diagnostic: "Data-diagnostic module helps to identify the causes of missing data."
  attachment_marker: "Attachment marker algorithm uses variance of a windowed signals data to mark the window as on/off body or improperly attached."
  battery_data_marker: "Battery data marker uses battery levels to determine whether the battery was down or device was powered off."
  packet_loss_marker: "Packet loss marker algorithm marks a window as packet-loss if received packets in a window is less than the acceptable packet loss threshold."
  sensor_unavailable_marker: "Sensor unavailable algorithm uses battery-off stream to analyze whether battery was actually powered off or a person walked away from the phone."
  app_availability_marker : "Phone battery data is continuously collected. If there is any missing mobile phone battery data then it would be considered as mobile app unavailable."
  sensor_failure: "Sensor is considered as failed if one of the sensors fails to capture signals."
  phone_screen_touch: "This algorithm is not part of data diagnostic core suite. This stream contains the duration when a participant was active on phone."



